server:
  port: 9000
spring:
  application:
    name: cards
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/" #If anything goes wrong with configserver, it won't throw any exception or error during startup (only warning)
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
