services:
  #Each of these services is going to be created inside its own network
  #To make sure that the intercommunication is working, we need to tag all these microservices under the same network

  accounts:
    image: "lassoued/accounts:1.0.0"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m #700mb memory max
    networks:
      - lassoued
  loans:
    image: "lassoued/loans:1.0.0"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - lassoued
  cards:
    image: "lassoued/cards:1.0.0"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - lassoued

networks:
  lassoued:
    driver: "bridge"