server:
  port: 8090
spring:
  application:
    name: loans
  profiles:
    active: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/loansdb}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted #instead of shutdown enabled
        #We needed include refresh for refreshing configs without restarting
      #We also used bus for spring cloud bus
  info:
    env:
      enabled: true
eureka:
  instance:
    preferIpAddress: true #to use ip address
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
#These will be displayed in eureka UI
info:
  app:
    name: "loans"
    description: "Lassoued Bank Loans Application"


