server:
  port: 8080
spring:
  application:
    name: accounts
  profiles:
    active: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/accountsdb}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/" #If anything goes wrong with configserver, it won't throw any exception or error during startup (only warning)
  rabbitmq: #These are default config of rabbit (can be deleted)
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

#    import: "configserver:http://localhost:8071/" if config server is mandatory
#Expose all management endpoints (health by default)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  #These are used to expose liveness and readiness used for dependance between config server and other microserver when starting with docker-compose. To let other MS wait for config server
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      access: unrestricted #instead of shutdown enabled
    #We needed include refresh for refreshing configs without restarting
        #We also used bus for spring cloud bus
  info:
    env:
      enabled: true
eureka:
  instance:
    preferIpAddress: true #to use ip address
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
#These will be displayed in eureka UI
info:
  app:
    name: "accounts"
    description: "Lassoued Bank Accounts Application"
    version: "1.0.0"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10 #How many requests it has initially monitor before it tried to change the status from closed to open
      permittedNumberOfCallsInHalfOpenState: 2 #Based on these requests (2 requests in our case), it can decide whether to go back to the open state or move to the closed state
      failureRateThreshold: 50 #if at lease 50% percent of my requests are failed then my circuit breaker pattern have to move to the open state
      waitDurationInOpenState: 10000 #10s to move to the half open state

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 500
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
#      ignoreExceptions:
#        - java.lang.NullPointerException
#      retryExceptions:
#        - java.util.concurrent.TimeoutException //works only with these exceptions