server:
  port: 8080
spring:
  application:
    name: accounts
  profiles:
    active: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/accountsdb}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/" #If anything goes wrong with configserver, it won't throw any exception or error during startup (only warning)
  rabbitmq: #These are default config of rabbit (can be deleted)
    host: localhost
    port: 5672
    username: guest
    password: guest

#    import: "configserver:http://localhost:8071/" if config server is mandatory
#Expose all management endpoints (health by default)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted #instead of shutdown enabled
    #We needed include refresh for refreshing configs without restarting
        #We also used bus for spring cloud bus
  info:
    env:
      enabled: true
eureka:
  instance:
    preferIpAddress: true #to use ip address
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
#These will be displayed in eureka UI
info:
  app:
    name: "accounts"
    description: "Lassoued Bank Accounts Application"
    version: "1.0.0"